difficulty_1:
  name: easy
  damage: 3
  tick_rate: 20

difficulty_2:
  name: medium
  damage: 5
  tick_rate: 20

difficulty_3:
  name: hard
  damage: 3
  tick_rate: 10

difficulty_4:
  name: extreme
  damage: 5
  tick_rate: 10

difficulty_5:
  name: impossible
  damage: 1
  tick_rate: 1
